volumes:
  appcache:

services:
  7daystodie:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "26900:26900/tcp"
      - "26900-26903:26900-26903/udp"
    volumes:
      - appcache:/home/7daystodie/app
      - ./mount:/home/7daystodie/data
